### ISSUE TITLE
Limit scanning area?

### ISSUE THREAD

**Issue by agordeev** [yannickl/QRCodeReader.swift#106]
Is it possible to limit the scanning area to small inner square?

**Comment by yannickl** [comment]
For the moment the `metadataOutput.rectOfInterest` property is not exposed.

Feel free to contribute to add it to the `QRCodeReader` object.

**Comment by AbdullahUsmani** [comment]
@yannickl Can I know when is the next release planned? I am using this library and need this feature urgently. :)

**Comment by yannickl** [comment]
@AbdullahUsmani I'm going to push the new version. :) I was waiting for some tests and feedbacks.

**Comment by yannickl** [comment]
The `v10.0.0` is released, and it provides the `rectOfInterest` property.

**Comment by AbdullahUsmani** [comment]
Thank you! Looks great! 😃 👏
