### ISSUE TITLE
Doesn't detect colored QR codes

### ISSUE THREAD

**Issue by odedharth** [yannickl/QRCodeReader.swift#107]
It doesn't detect colored QR code such as this one:
https://www.evernote.com/l/ADnyv1c2Oz5KkYEIHnqxQ6gvPY2LAGoZ-0w

This code is detected by other QR detection apps I've found on the App Store.

After doing some digging, I've found the reason is probably the contrast of the white & blue colors. Any idea how to increase the contrast? Is there a way to add a filter?

**Comment by odedharth** [comment]
I've noticed that it detects the code only when you the camera is further away and the code is very small. Any idea why?

**Comment by yannickl** [comment]
Hi @odedharth,

Yes indeed, by increasing the contrast it works fine.

The library is based on the `AVFoundation` and so I have no control about it. May be we should try to change the camera settings (exposure, brightness, contrast, white balance factors)?

I don't have a lot of time, if you have may be you can help? (see https://www.objc.io/issues/21-camera-and-photos/camera-capture-on-ios/)
