### ISSUE TITLE
Xcode 9 beta 4, Extra argument 'mediaType' in call

### ISSUE THREAD

**Issue by farshadjahanmanesh** [yannickl/QRCodeReader.swift#110]
return AVCaptureDevice.defaultDevice(withDeviceType: .builtInWideAngleCamera, mediaType: AVMediaTypeVideo, position: .front)

cant run the project failed with this error
Extra argument 'mediaType' in call

i removed that line of code and build go successfully

**Comment by yannickl** [comment]
Related to #105

**Comment by yannickl** [comment]
Thank you for the report, I'll check that later

**Comment by yannickl** [comment]
Fix in the v8.0.0
