### ISSUE TITLE
black screen in Swift 4

### ISSUE THREAD

**Issue by reshadf** [yannickl/QRCodeReader.swift#111]
I have got the library through cocoapods on a Swift4 project. However, the screen is black. Is this a known issue, or do I have made some configuration? ( I took most of the custom layout code from an old project )

**Comment by KashishGoel** [comment]
What was the solution? Encountering the same problem

**Comment by reshadf** [comment]
Hey this issue wasn't due to Swift4 but to some code refactoring in the QRCodeScanner. 

Basically the issue is that it doesn't buffer a preview, if I am correct you need to make sure you have the following in the class where you inherit QRCodeReaderDisplayable

`   @objc func orientationDidChange() {
        setNeedsDisplay()
        overlayView?.setNeedsDisplay()
        
        if let connection = reader?.previewLayer.connection, connection.isVideoOrientationSupported {
            let orientation                    = UIDevice.current.orientation
            let supportedInterfaceOrientations = UIApplication.shared.supportedInterfaceOrientations(for: nil)
            
            connection.videoOrientation = QRCodeReader.videoOrientation(deviceOrientation: orientation, withSupportedOrientations: supportedInterfaceOrientations, fallbackOrientation: connection.videoOrientation)
        }
    }`

and in the addComponents() function add 
`NotificationCenter.default.addObserver(self, selector: #selector(QRScanView.orientationDidChange), name: .UIDeviceOrientationDidChange, object: nil)`

**Comment by KashishGoel** [comment]
Oh interesting, I actually don't use a preview. I tried setting a custom overlay and kept coming across a black screen. I think I'm implementing this incorrectly. 

`class QROverlay: UIView, QRCodeReaderDisplayable {
    let cameraView: UIView            = UIView()
    let cancelButton: UIButton?       = UIButton()
    let switchCameraButton: UIButton? = SwitchCameraButton()
    let toggleTorchButton: UIButton?  = ToggleTorchButton()
    var overlayView: UIView?          = UIView()
    
    func setupComponents(showCancelButton: Bool, showSwitchCameraButton: Bool, showTorchButton: Bool, showOverlayView: Bool) {
        let overlay = UIImage(named: "qrOverlay")
        let imageView = UIImageView(image: overlay)
        imageView.frame = (self.overlayView?.frame)!
        overlayView?.addSubview(imageView)
    }
}


lazy var qrCodeReaderViewController: QRCodeReaderViewController = {
        let builder = QRCodeReaderViewControllerBuilder { builder in
            builder.reader                 = QRCodeReader(metadataObjectTypes: [AVMetadataObjectTypeQRCode])
            builder.showTorchButton        = false
            builder.showSwitchCameraButton = false
            builder.showOverlayView = true
            let readerView = QRCodeReaderContainer(displayable: QROverlay())
            
            builder.readerView = readerView
        }

        return QRCodeReaderViewController(builder: builder)
    }()

`

**Comment by priyankakanse123** [comment]
Its not working for me.. I have taken pull latest version that is 8.2.0
Any other solution??
Still appearing black part on my screen but functionality working exactly fine....
