### ISSUE TITLE
Localize Cancel button

### ISSUE THREAD

**Issue by CeceXX** [yannickl/QRCodeReader.swift#114]
Hi, 

Is there any way I can localize the "Cancel" string button?

Thanks,
Cesare

**Comment by yannickl** [comment]
Hi,

You can change the "Cancel" string via the `cancelButtonTitle ` property of the `QRCodeReaderViewControllerBuilder` when you init the `QRCodeViewController`:

```swift
let builder = QRCodeReaderViewControllerBuilder {
  $0.reader = QRCodeReader(metadataObjectTypes: [AVMetadataObjectTypeQRCode], captureDevicePosition: .back)
  $0.cancelButtonTitle = "Cancel"
}
    
let vc = QRCodeReaderViewController(builder: builder)
```

**Comment by CeceXX** [comment]
Thanks so much Yannick!
