### ISSUE TITLE
isAvailable() -> Bool crashes on simulator

### ISSUE THREAD

**Issue by Schaefers** [yannickl/QRCodeReader.swift#116]
`let captureDevice = AVCaptureDevice.default(for: AVMediaType.video)` is nil on Simulator and maybe some iPod Touch models without camera. 

So it crashes when unwrapping here `AVCaptureDeviceInput(device: captureDevice!)`

**Comment by kuchmiyalex** [comment]
Same thing, need to guard captureDevice optional

**Comment by yannickl** [comment]
Thank you for the report!

I don't when the issue did occurred, but it is now fixed! 👍

**Comment by Schaefers** [comment]
The function I was talking about is this one, which still force unwraps the `captureDevice`.. https://github.com/yannickl/QRCodeReader.swift/blob/6231618258b95a6ec6a8bc6397610e228a997a7b/Sources/QRCodeReader.swift#L316

**Comment by yannickl** [comment]
Sorry for the inconvenience, this is fixed.
