### ISSUE TITLE
Breaking change and docs not 

### ISSUE THREAD

**Issue by Jaspur** [yannickl/QRCodeReader.swift#118]
Wauw.. such a breaking change in the latest tagged version and the docs aren't clear how to do it now..

```
$0.reader = QRCodeReader(metadataObjectTypes: [AVMetadataObjectTypeQRCode], captureDevicePosition: .back)
```
Fails; Type of expression is ambiguous without more context

**Comment by yannickl** [comment]
This is not an update from the `QRCodeReader.swift`, but a Swift4 update. The `AVMetadataObjectTypeQRCode` is now an `AVMetadataObject.ObjectType.qr`. So in your case, this is just: 

```swift
$0.reader = QRCodeReader(metadataObjectTypes: [.qr], captureDevicePosition: .back)
```

Have you updated your project to Swift4?
