### ISSUE TITLE
Camera is not display, but scan is work, case of custom interface

### ISSUE THREAD

**Issue by purplecofe** [yannickl/QRCodeReader.swift#120]
update to swift 4 version before is work fine

but update to swift 4 version after is not work

how can i fix it?

source code here
https://gist.github.com/purplecofe/c9ea540760a990bf5aeec62b4507bee8

thanks for your help

**Comment by lhchome** [comment]
me too !

**Comment by yannickl** [comment]
You have to keep a reference to the `QRCodeReader` and add its previous layer by yourself in your view:

 - https://github.com/yannickl/QRCodeReader.swift/blob/f7f387d03124fc66463c396f6e2230f0ebc71763/Sources/QRCodeReaderView.swift#L77
 - https://github.com/yannickl/QRCodeReader.swift/blob/f7f387d03124fc66463c396f6e2230f0ebc71763/Sources/QRCodeReaderView.swift#L118
 - https://github.com/yannickl/QRCodeReader.swift/blob/f7f387d03124fc66463c396f6e2230f0ebc71763/Sources/QRCodeReaderView.swift#L183

**Comment by Jackhammer42** [comment]
I am seeing this behavior too. sometimes. for now, i was not able to reproduce it reliably.

**BUT**: I am using the code from the example project to instantiate the `QRCodeReaderViewController` from the pod files:

```
lazy var reader: QRCodeReader = QRCodeReader()
    lazy var readerVC: QRCodeReaderViewController = {
        let builder = QRCodeReaderViewControllerBuilder {
            $0.reader = QRCodeReader(metadataObjectTypes: [AVMetadataObject.ObjectType.qr], captureDevicePosition: .back)
            $0.showTorchButton = true
        }
        
        return QRCodeReaderViewController(builder: builder)
    }()
```

As far as I understand in this 'standard' ViewController the proposed fix for the behavior is already included, right?

I am using Xcode 9 and swift 4. My test device is a iphone 6s plus running ios 9.3.5

**Comment by lai3d** [comment]
Me too!

**Comment by kangert** [comment]
The same problem. An unmodified code, freshly downloaded from here. Cannot reproduce it reliably, but it occurs in about 20% of the app's starts. The app has to be killed to get an other attempt (cancel button will not help).

Tested on iPhone 6s (iOS 11) and iPhone 4s (iOS 9), Xcode 9.1.

**Comment by kangert** [comment]
Maybe it's coincidence, but it seems it happens mainly when the device is connected to Xcode. Can anyone confirm this observation?

**Comment by yannickl** [comment]
To be sure, the issue occurs when your are using the provided view controller or in the example project with the embedded view?

Is it related to #125?

**Comment by kangert** [comment]
1) Yes.

2) Hard to say. I'm unable to reproduce it in preview mode. However, if the "modal mode" is stuck in the black screen (black screen with icons and the rectangle), the preview mode works just fine along with it. There is also no info about scanner behavior in #125. Here, the scanner works ok, only the "live view" does not work, so you have to scan it blindly. This state is permanent for the session (cancel button or scanned QR code does not change the situation, only hard restart of the app - the app has to be killed or redeployed).

**Comment by Jackhammer42** [comment]
In QRCodeReader.swift/Sources/QRCodeReaderView.swift I changed line 74 from `private weak var reader: QRCodeReader?` to `var reader: QRCodeReader?`. Since that change, everything works fine (aka i was not able to reproduce the described behavior anymore).

**Comment by yannickl** [comment]
@Jackhammer42 so the issue came from the fact the `reader` var is `weak`?

I'll investigate that, because I don't know why it happens.

**Comment by Jackhammer42** [comment]
yes, indeed.

**Comment by rustydr34m** [comment]
![image uploaded from ios](https://user-images.githubusercontent.com/12074801/33242889-9c443c94-d2ec-11e7-9bc2-4535a02796a0.png)

I have the same problem. Did you find a solution?

**Comment by rustydr34m** [comment]
I'dont know why but when set readerVC in viewDidAppear it's stable.
I have done hundreds of tests today and it never happened. Any ideas?

  override func viewDidAppear(_ animated: Bool) {
      
        readerVC = {
            let builder = QRCodeReaderViewControllerBuilder {
                $0.reader = QRCodeReader(metadataObjectTypes: [AVMetadataObject.ObjectType.qr], captureDevicePosition: .back)
                $0.showTorchButton = true
             
            }
            
            return QRCodeReaderViewController(builder: builder)
        }()
    }

**Comment by yannickl** [comment]
@rustydr34m the last release don't fix your issue?

You still have to init the reader in the `viewDidAppear`?

**Comment by rustydr34m** [comment]
@yannickl 
private weak var reader: QRCodeReader? to private var reader: QRCodeReader? not fix the problem,

But when init the reader in the viewDidAppear (reader still private weak var reader: QRCodeReader?) problem solved for me. But I don't know why.

**Comment by ruoyuruoshui** [comment]
@yannickl 
`previewLayer` is initial twice when i debug

> If a property marked with the lazy modifier is accessed by multiple threads simultaneously and the property has not yet been initialized, there is no guarantee that the property will be initialized only once.

**Comment by yannickl** [comment]
@ruoyuruoshui thank you for pointing me this point because I was sure it was atomic. I'll investigate that.

**Comment by vcsabi** [comment]
Still have this issue any news about this? I would really want to use it!

**Comment by yannickl** [comment]
@vcsabi is the issue still there with the `v8.1.0`?

**Comment by vcsabi** [comment]
@yannickl Really appreciate your fast response, and yes with the latest version

**Comment by rustydr34m** [comment]
in iphonex does not work at all

**Comment by skdevil** [comment]
@rustydr34m  Did you find any solution ? It's same for me also.

**Comment by dollykosmos** [comment]
Please provide solution for "Camera is not display, but scan is work, case of custom interface"

**Comment by RexNexstream** [comment]
Have the same problem

**Comment by sedoyjan** [comment]
> Have the same problem

And me

**Comment by sedoyjan** [comment]
@yannickl Please provide solution for "Camera is not display, but scan is work, case of custom interface"
