### ISSUE TITLE
Camera is not getting displayed but QR is scanned in case of "Scan in Preview" 

### ISSUE THREAD

**Issue by iOSDevAkshay** [yannickl/QRCodeReader.swift#121]
latest code : Version 8.0.3
it is not duplicate of #120  , please help , much needed .
Thanks in advance

**Comment by yannickl** [comment]
The v8 only works with Xcode9 and Swift4. If you are working with Xcode8 and Swift3 you should use the `version 7`.

**Comment by iOSDevAkshay** [comment]
Thanks

**Comment by yannickl** [comment]
Maybe #125 related?
