### ISSUE TITLE
Unable to compile project from QR Reader pod?

### ISSUE THREAD

**Issue by realtimez** [yannickl/QRCodeReader.swift#122]
Hi,

I installed the pod and ran the workspace but the project wont compile. I didn't even use any code yet related to it.

Attached a couple of screenshots that shows the issues: 

<img width="270" alt="screen shot 2017-10-28 at 20 16 48" src="https://user-images.githubusercontent.com/2002392/32136806-6317d146-bc1d-11e7-8336-e6725661d738.png">
<img width="1038" alt="screen shot 2017-10-28 at 20 19 33" src="https://user-images.githubusercontent.com/2002392/32136808-64b783de-bc1d-11e7-9995-a5648843905a.png">

Thanks!

**Comment by yannickl** [comment]
It seems you are using a wrong combination pod/xcode/swift version.

The `v8.x` works with Xcode9 and Swift4. For older version you must use the `v7.x`.

**Comment by realtimez** [comment]
Yep I'm on Xcode 9 and Swift 4:

<img width="528" alt="screen shot 2017-10-28 at 20 44 27" src="https://user-images.githubusercontent.com/2002392/32137012-e253c372-bc20-11e7-82ca-3442569fbf6b.png">
<img width="507" alt="screen shot 2017-10-28 at 20 44 33" src="https://user-images.githubusercontent.com/2002392/32137013-e27e4926-bc20-11e7-8ff5-9038a776bcec.png">

Anything else that might have caused it to fail compilation?

**Comment by yannickl** [comment]
That's weird, can you compile the `QRCodeReader.swift` in standalone?

What is your Cocoapods version?

**Comment by adozer** [comment]
I have the same problem. My cocoa pods version is 1.3.1. 
Podfile is 

> target 'TargetName' do
>   use_frameworks!
> 
> ...
>   pod 'GoogleMaps'
>   pod 'QRCodeReader.swift', '~> 8.0.3'
> ...
>   pod 'GoogleSignIn'
> end

**Comment by Jerms641** [comment]
I was getting the same errors under the same conditions, the work around I used for this one is to go into the Pods Project in the Project Navigator, select the QRCodeReader.swift Target, go to the Build Settings tab and find the Swift Compiler - Language section. Then in there change the Swift Language Version to Swift 4.0, for me it was set to Swift 3.2.
<img width="514" alt="screen shot 2017-11-16 at 2 01 44 pm" src="https://user-images.githubusercontent.com/15915487/32871703-b86adb3a-cad6-11e7-8dc9-e6a12ea4437c.png">

**Comment by yannickl** [comment]
@Jerms641 thank you for the workaround!

This is issue does not seem to occurred very often, and I think this is an Xcode / CocoaPods configuration issue, so I close the issue.
