### ISSUE TITLE
Scan in preview view appears white

### ISSUE THREAD

**Issue by riki-dexter** [yannickl/QRCodeReader.swift#125]
Also in your example project, sometimes preview view appears white after pressing Scan in Preview button

**Comment by yannickl** [comment]
Thank you for the report! Are you able to defines a workflow which produce this behaviour each time?

(it will be easier to debug)

**Comment by riki-dexter** [comment]
Hi yannickl,
It isn’t systematic, randomly preview view appears rotated or totally white.
Not so often, but occurs.
I’m using last Xcode and Swift 4.
Thank you

**Comment by yannickl** [comment]
You noticed 2 different issues:
 - the camera rotation
 - the blank screen

For the first one, I have to update the code to determine the initial orientation of the device when it is faced up.
For the second one, it seems to be a wrong workflow initialisation. Indeed the `previewLayer` have to be already attached to the view before to start the scan else it does not work. :/ I've updated the example project. Is the issue still occurs for you?

**Comment by riki-dexter** [comment]
Hi @yannickl,
I'll try this new version and I'll report if this issue still occurs.
Thank you!
