### ISSUE TITLE
Respect Safe Area

### ISSUE THREAD

**Issue by Sorix** [yannickl/QRCodeReader.swift#128]
At iPhone X buttons overlapping safe areas (e.g. Cancel button placed over Apple's exit button-line).

**Comment by fahadkhanWR** [comment]
Also on iPhone X camera sometimes appear and sometimes doesn't.

**Comment by andre991** [comment]
Same here.

**Comment by Alkalouti** [comment]
any update I have the same issue

**Comment by yannickl** [comment]
It should be ok with the new release.
