### ISSUE TITLE
How to create qr code focus effect?

### ISSUE THREAD

**Issue by datomnurdin** [yannickl/QRCodeReader.swift#13]
How I can create QR Code focus effect like picture below?

![screen322x572](https://cloud.githubusercontent.com/assets/5416242/6939881/89f6c8d6-d8a3-11e4-9a44-3fafe69dc880.jpeg)

**Comment by yannickl** [comment]
You will have to create your own view controller with your custom overlay view like https://github.com/yannickl/QRCodeReader.swift/blob/master/QRCodeReader/QRCodeViewController.swift

**Comment by datomnurdin** [comment]
Noted.
