### ISSUE TITLE
Is there any way to get the decoded barcode as Data?

### ISSUE THREAD

**Issue by wuftymerguftyguff** [yannickl/QRCodeReader.swift#132]
Hi,

I only seem to be able to scan/decode barcodes that decode to a valid String.

Sometimes I need arbitrary data in my barcodes.

Jeff

**Comment by yannickl** [comment]
Hi, what kind of data? Because in a string you can encode everything? With the `AVMetadataMachineReadableCodeObject` we can only return a string value.

**Comment by wuftymerguftyguff** [comment]
[sqrl-id-output.pdf](https://github.com/yannickl/QRCodeReader.swift/files/1817066/sqrl-id-output.pdf)

Attached is a PDF with an example QR Code.

I can read this QR with ZBAR under iOS and countless other QR Readers on iOS and other platforms, but not with anything based on AVFoundation because of the coercion of the raw data into a String.

This post on SO talks about using a private property to get around the issue, but no one really wants to go down that route lightly. 

https://stackoverflow.com/questions/32429480/read-binary-qr-code-with-avfoundation

**Comment by yannickl** [comment]
I don't want to use private APIs because it'll breaks the app submission process to the App Store. So you should submit a radar to Apple.

**Comment by nderkach** [comment]
You can just encode data as a Base64 string for example.
