### ISSUE TITLE
Not able to scan any QR Code

### ISSUE THREAD

**Issue by NALAWALAMURTUZA** [yannickl/QRCodeReader.swift#134]

**Comment by NALAWALAMURTUZA** [comment]
Please Provide any solution for scanning QR Code.

**Comment by yannickl** [comment]
Have you tried the example project?

**Comment by NALAWALAMURTUZA** [comment]
Yes, I got a solution. I tried the example in my second device. and run successfully. I think there is some issue with my first device. thank you for a response.
