### ISSUE TITLE
 Argument labels '(_:)' do not match any available overloads -- after swift 3 migrate

### ISSUE THREAD

**Issue by SheikhZayed** [yannickl/QRCodeReader.swift#138]
`            self.readerVC = QRCodeReaderViewController([AVMetadataObjectTypeQRCode])
`

the code given above was working fine in swift 2.3,but after migrate im getting the following issue,whats the replacement

 Argument labels '(_:)' do not match any available overloads

**Comment by yannickl** [comment]
Use the `v7.x` for Swift 3. The `v8.x` works only in Swift 4.
