### ISSUE TITLE
After upgrading "Type of expression is ambiguous without more context"

### ISSUE THREAD

**Issue by renege** [yannickl/QRCodeReader.swift#150]
Hello,
This code worked fine before, but after upgrading not anymore:
**Type of expression is ambiguous without more context**
```
    lazy var readerVC: QRCodeReaderViewController = {
        let builder = QRCodeReaderViewControllerBuilder {
            $0.reader = QRCodeReader(metadataObjectTypes: [AVMetadataObjectTypeQRCode], captureDevicePosition: .back)
            let readerView = QRCodeReaderContainer(displayable: MyReaderView())
            
            $0.readerView = readerView
        }
        
        return QRCodeReaderViewController(builder: builder)
    }()
```

And the other error:
```
class MyReaderView: UIView, QRCodeReaderDisplayable {
```
Gives: ```Type 'MyReaderView' does not conform to protocol 'QRCodeReaderDisplayable'```
Xcode gives the option:

> Type 'MyReaderView' does not conform to protocol 'QRCodeReaderDisplayable'
> Do you want to add protocol stubs?
When I click on to fix that, it gives me this, but I don't know what to do with it:
```
 func setNeedsUpdateOrientation() {
        <#code#>
    }
```

**Comment by yannickl** [comment]
Is the error still happens? I'm closing the issue and I'll reopen it if necessary.

**Comment by crysptos** [comment]
still does
