### ISSUE TITLE
Notification name updated in Swift 4.2

### ISSUE THREAD

**Issue by petkotodorov** [yannickl/QRCodeReader.swift#152]
UIDevice.orientationDidChangeNotification has changed to NSNotification.Name.UIDeviceOrientationDidChange in Swift 4.2. It is causing compiler error.
<img width="852" alt="screen shot 2018-09-24 at 2 07 35 pm" src="https://user-images.githubusercontent.com/13046545/45949118-5c410500-c003-11e8-8f76-50f59f381463.png">

**Comment by yannickl** [comment]
The `NSNotification.Name.UIDeviceOrientationDidChange` is the old version, in Swift 4.2 you have to use the `UIDevice.orientationDidChangeNotification`. Have you properly updated your project settings?

If you want the Swift 4.0 version you should use the v8.x version of the library.
