### ISSUE TITLE
Compilation error after updating the pod to version 9.0.0

### ISSUE THREAD

**Issue by nico75005** [yannickl/QRCodeReader.swift#153]
I get a compilation error on `UIDevice.orientationDidChangeNotification` in `QRCodeReader.swift` (line 165).

Am I the only one as I didn't see any mention of this?

A fix seems to update it with `NSNotification.Name.UIDeviceOrientationDidChange`

**Comment by yannickl** [comment]
The v9.0.0 is compatible with Swift 4.2.

See #152.

**Comment by nico75005** [comment]
Indeed, I don't know why it was on 4.0

Thanks
