### ISSUE TITLE
Use of undeclared type 'QRCodeReaderViewControllerDelegate'

### ISSUE THREAD

**Issue by datomnurdin** [yannickl/QRCodeReader.swift#16]
I don't know why it happens like this after I updated my xcode  to 6.3.1 and pod. I got this strange error message suddenly even your library already included inside pod.

```
/Users/MNurdin/Documents/iOS/xxxxx/Controllers/MethodViewController.swift:13:47: Use of undeclared type 'QRCodeReaderViewControllerDelegate'
```

My code

```
import UIKit
import CoreData
import AVFoundation

class MethodViewController: UIViewController, QRCodeReaderViewControllerDelegate { //error here
```

Please advice. Thank you.

**Comment by yannickl** [comment]
If you use Cocoapods, it will generate the `QRCodeReader.swift` project as a framework so you need import it into your file like that `import QRCodeReader`.

**Comment by datomnurdin** [comment]
It works!! why it happen on xcode 6.3 suddenly?

**Comment by yannickl** [comment]
I don't know, It should work like that since Xcode 6.0 and cocoapod 0.36. I don't know why it happens just now for you. :/

**Comment by datomnurdin** [comment]
I see. BTW thanks again.
