### ISSUE TITLE
pod updated to 9.0.1 getting error Value of type 'QRCodeReaderViewControllerBuilder' has no member 'rectOfInterest'

### ISSUE THREAD

**Issue by 22Round** [yannickl/QRCodeReader.swift#160]
I am playing with QRCodeReader.swift, after pod update I get this error: 

> Value of type 'QRCodeReaderViewControllerBuilder' has no member 'rectOfInterest'

<img width="1535" alt="screen shot 2019-01-10 at 20 37 16" src="https://user-images.githubusercontent.com/5682469/50982854-8fa69180-1517-11e9-93bd-c4a6b3dd375b.png">

**Comment by yannickl** [comment]
This is because the `9.x` version the `QRCodeReaderViewControllerBuilder` has no member `rectOfInterest`.

The `rectOfInterest` property will be available in the next version. If you want to use the next version you can update your `Podfile` like this:

```ruby
pod 'QRCodeReader.swift', :git => 'https://github.com/yannickl/QRCodeReader.swift', :branch => 'master'
```
