### ISSUE TITLE
Provide implementation for this customization

### ISSUE THREAD

**Issue by vaidehiH** [yannickl/QRCodeReader.swift#163]
func setupComponents(with builder: QRCodeReaderViewControllerBuilder) {
}

**Comment by yannickl** [comment]
Sorry I don't understand your motivation?

If you need an implementation example you can take a look at the [`QRCodeReaderView`'s one](https://github.com/yannickl/QRCodeReader.swift/blob/e3dab15f3fc81962410ef8a6cc534b9917c73a4a/Sources/QRCodeReaderView.swift#L76)
