### ISSUE TITLE
has anyone ever got this to work?  

### ISSUE THREAD

**Issue by Nathan187** [yannickl/QRCodeReader.swift#167]
i played around with this for 45 minutes and have yet to get it to read a QR code.  plus it's annoying to get the rectangle to a decent size.  some predetermined sizes would have been helpful

**Comment by yannickl** [comment]
Have you tried to "play" with the example project?

The `rectOfInterest` property uses relative positions/dimensions. If you view is 100x100 and the `rectOfInterest` is *{x: 0.2, y: 0.2, w: 0.6, h: 0.6}* the scanned rectangle will be *{x: 20, y: 20, w: 60, h: 60}*.
