### ISSUE TITLE
How to get result in as NSDictionary.

### ISSUE THREAD

**Issue by Mitesh-Mewada** [yannickl/QRCodeReader.swift#168]
Hey @yannickl  great work and thanks for save my time,
        I completely integrate this lib.  and it's work perfectly but wen i got QR Response i cant handle it, i want to get result in **NSDictionary** how to convert ? 

@All any have solution ? Please help me.

**Comment by yannickl** [comment]
The callback returns a [`QRCodeReaderResult`](https://github.com/yannickl/QRCodeReader.swift/blob/b389c41ae090a33a4c6dd3db37b8235f776ce34f/Sources/QRCodeReaderResult.swift). You can manage the `value` and `metadataType` as you want then.

**Comment by Mitesh-Mewada** [comment]
@yannickl  i change value as NSDictionary also metadataType but i facing my of file error and i cant solve and i facing  

> QRCodeReader.swift

 `public 


`func` metadataOutput(_ output: AVCaptureMetadataOutput, didOutput metadataObjects: [AVMetadataObject], from connection: AVCaptureConnection) {
    sessionQueue.async { [weak self] in
      guard let weakSelf = self else { return }

      for current in metadataObjects {
        if let _readableCodeObject = current as? AVMetadataMachineReadableCodeObject {
          if _readableCodeObject.stringValue != nil {
            if weakSelf.metadataObjectTypes.contains(_readableCodeObject.type) {
                guard weakSelf.session.isRunning, let sVal = _readableCodeObject.stringValue else { return }

              if weakSelf.stopScanningWhenCodeIsFound {
                weakSelf.session.stopRunning()

                DispatchQueue.main.async {
                  weakSelf.lifeCycleDelegate?.readerDidStopScanning()
                }
              }

              let scannedResult = QRCodeReaderResult(value: sVal, metadataType:_readableCodeObject.type.rawValue)

              DispatchQueue.main.async {
                weakSelf.didFindCode?(scannedResult)
              }
            }
          }
        }
        else {
          weakSelf.didFailDecoding?()
        }
      }
    }
  }` .   i got this error **Cannot convert value of type 'String' to expected argument type 'NSDictionary'** form        
                                      

> let scannedResult = QRCodeReaderResult(value: sVal, metadataType:_readableCodeObject.type.rawValue)



how to resolve this issue if you have done so please share with  me code .
