### ISSUE TITLE
The QR Code reader is too FAST!

### ISSUE THREAD

**Issue by shaolinjr** [yannickl/QRCodeReader.swift#18]
The QR Code read is too fast, I can't even position my phone correctly, so it often get a nil result back.
Is there any way to set a delay or a NSTimer to give the app more time to focus and positon the phone correctly?

**Comment by yannickl** [comment]
Hi,

Sorry for the late, I just added a `startScanningAtLoad` parameter in the init methods to allow you to delay the start of scanning.

You can use it like that:
```swift
var reader = QRCodeReaderViewController(metadataObjectTypes: [AVMetadataObjectTypeQRCode], startScanningAtLoad: false)

reader.modalPresentationStyle = .FormSheet

presentViewController(reader, animated: true, completion:  { (finished) in
  reader.startScanning()
})
```

Best,

Yannick
