### ISSUE TITLE
Front facing camera not scanning

### ISSUE THREAD

**Issue by lzumbach** [yannickl/QRCodeReader.swift#20]
Version: fc62c9e514a3c80bbec92d1c47efde66b83d60bc
The front facing camera on my iPhone 6 or new iPad Air can't seem to focus in to scan a QR Code or Code 39.   It looks like the image is reversed when scanning the code39.  Also it would be nice if there was a separate branch for XCode 6 and Swift 1.2.

**Comment by yannickl** [comment]
I don't understand, I tried it with my iPhone 6 and it works great. Have you an example project or a protocol that can reproduce the problem?

Anyway I move the last commits into a `swift2` branch, so now the master is clean. :)

**Comment by cody1024d** [comment]
@yannickl I don't mean to resurrect this, but I am having a similar problem on my Ipad device.  It seems that, in the front camera, the preview is reversed, and is seemingly not reading the serial number.

**Comment by yannickl** [comment]
@cody1024d is a random problem or is happens all the time? By the same way have you a sample code and/or a sample 1d code please?

**Comment by cody1024d** [comment]
It happens consistently.  I can provide you a small code sample, but the project I'm using this library in is closed-source.  Essentially though, I'm using the library exactly as the demo code suggests.

The main thing, that perhaps influences this, is that the application I'm using this with is set to land-scape only.  Perhaps that has something to do with it (the screen orientation)?

IOS 9.3.1
Ipad Air 2

**Comment by yannickl** [comment]
@cody1024d I have some that are in landscape mode/front camera only and it works great (but I only scan QRCode). May be for other code types it is more sensitive.

However that's not normal that the preview is reversed. The preview is reversed when you hold the iPad or when it is "face up"?

**Comment by cody1024d** [comment]
Yeah, specifically, the preview is reversed when I am holding the Ipad in such that the home button is on the right, and the front-facing camera is on the left.  If I get some time, I can maybe rip out some of our code, and create a small project with it.  Unfortunately, though, I'm on a pretty tight deadline, and probably won't have time to do that for a bit.

If there's any other information that I could provide, that may be helpful for you though, let me know :)
