### ISSUE TITLE
camera cant detect qr

### ISSUE THREAD

**Issue by koolll** [yannickl/QRCodeReader.swift#21]
Hi i try generate vcard qr .But when the qr content is larger, the qr reader is not able to detect. Any solution?example 
http://postimg.org/image/g2t534lzb/

**Comment by yannickl** [comment]
Hi, 

first of all sorry for the late.

I tried to scan your QRCode with an iPhone 6 and an iPad Mini Retina 2; it works great. Which kind of devices are you using?
