### ISSUE TITLE
Crash when calling QRCodeReader.supportsMetadataObjectTypes()

### ISSUE THREAD

**Issue by shmidt** [yannickl/QRCodeReader.swift#22]
It's strange and I personally can't reproduce it, however I can see that many users have a crash on line:

```swift 
if QRCodeReader.supportsMetadataObjectTypes() {...}
```

![screen shot 2015-07-14 at 1 46 14 pm](https://cloud.githubusercontent.com/assets/1472370/8684700/c575146c-2a2e-11e5-8688-956d6ef82426.png)

**Comment by yannickl** [comment]
Hi,

Thank you for the report. I've took a look into the code and I seen nothing wrong, I need more time to investigate that.
