### ISSUE TITLE
customisation of a scanner view

### ISSUE THREAD

**Issue by maksTheAwesome** [yannickl/QRCodeReader.swift#23]
I kinda need only a scanner view (no cancel button and no switch to front camera button) to be displayed on a screen. So I added this method:

public func returnCameraView () -> UIView {
        return cameraView;
    }

I believe that adding only a clean scanner view to my view controller would be more preferable for the component.

**Comment by yannickl** [comment]
Hi,

the cameraView is a composition of the `codeReader.previewLayer` and the overlay. If you want only have the camera view you can add the `codeReader.previewLayer` directly as sub layer of your view.
