### ISSUE TITLE
does not conform to protocol qrcodereaderviewcontrollerdelegate

### ISSUE THREAD

**Issue by arn00s** [yannickl/QRCodeReader.swift#24]
Hi all,

I've integrated using the classes, because CocoaPods didn't work.
Now I'm having this error : does not conform to protocol qrcodereaderviewcontrollerdelegate

And here's my class beginning code :
    class DeskBookingViewController: UIViewController, QRCodeReaderViewControllerDelegate, BookableDelegate {

What's wrong here ?
Thanks,

**Comment by yannickl** [comment]
Hi,

The error means you didn't implemented the `QRCodeReaderViewControllerDelegate` methods. Have you added these methods to your class?

```swift
func reader(reader: QRCodeReaderViewController, didScanResult result: String) {
}

func readerDidCancel(reader: QRCodeReaderViewController) {
}
```

**Comment by arn00s** [comment]
Hi @yannickl , thanks for your reply.
In fact I was using : 
```
    func reader(reader: QRCodeReader, didScanResult result: String) {
        self.dismissViewControllerAnimated(true, completion: nil)
    }
    
    func readerDidCancel(reader: QRCodeReader) {
        self.dismissViewControllerAnimated(true, completion: nil)
    }
```
instead of : 
```
    func reader(reader: QRCodeReaderViewController, didScanResult result: String) {
        self.dismissViewControllerAnimated(true, completion: nil)
    }
    
    func readerDidCancel(reader: QRCodeReaderViewController) {
        self.dismissViewControllerAnimated(true, completion: nil)
    }
```

now it's working fine :+1:
