### ISSUE TITLE
I want to run the next line after get the QR code.

### ISSUE THREAD

**Issue by christopher1215** [yannickl/QRCodeReader.swift#25]
I'm going to run its next line after get QR code.
However, my code is already run the next line while show the camera view.
Help me, please. Sorry for my bad english.
My code is as follows.

```swift
func myFunc(){
  getQRCode()
  if self.myQRCode == nil {  // self.myQRCode always hasn't readed code ...?????
.......
  } else {
  
  }
}
func getQRCode(){
  reader.delegate = self

  // Or by using the closure pattern
  reader.completionBlock = { (result: String?) in
    self.myQRCode = result
  }

  // Presents the reader as modal form sheet
  reader.modalPresentationStyle = .FormSheet
  presentViewController(reader, animated: true, completion: nil)
}
```

**Comment by yannickl** [comment]
Hi,

The scan is asynchronous so when you call the `getQRCode` method it does not wait for a response.

Here an example how to resolve your issue:
```swift
func myFunc() {
  // Scan callback
  reader.completionBlock = { (result: String?) in
    if let _result = result {
       println("Scanned code: \(_result)")
    }
    else {
      println("No code found")
    }
  }

  presentViewController(reader, animated: true, completion: nil)
}
```

**Comment by christopher1215** [comment]
I'm sorry.
The Function "myFunc" has to return the boolean value and the value relates to gotten QR Code.
In other words, "myFunc" has to return the result that processed by gotten QR code.
How can I do? Sorry for your trouble.
I'm going to make the function as follows.
func myFunc() -> Bool{
  var tmpFlag: Bool = false
  reader.completionBlock = { (result: String?) in
    if let _result = result {
       println("Scanned code: \(_result)")
       tmpFlag = checkQRCode(result)
    }
    else {
      println("No code found")
    }
  }

  presentViewController(reader, animated: true, completion: nil)
  return tmpFlag
}

**Comment by yannickl** [comment]
You can't do that easily because of the async callback.

The QRCodeReader runs into the main thread so if you block it by waiting a result your interface will be frozen and you should not do that.

Why the callback does not suit your needs?

**Comment by christopher1215** [comment]
Thank you for your kind reply.
