### ISSUE TITLE
 iPhone 6 is not supported?

### ISSUE THREAD

**Issue by woderchen** [yannickl/QRCodeReader.swift#28]
Hi
I'm using this great scan tool to implement my app. very nice and fast.
no problem if I use iPhone 5s to scan QR code.
but once I use iPhone 6 to scan,  the API of QRCodeReader.isAvailable() returns false. could you tell me why? thanks

**Comment by yannickl** [comment]
Hi,

I have an iPhone 6 and it works fine. Have you authorized the camera in your setting?

**Comment by woderchen** [comment]
thanks for your feedback, the message was send by my user, i will confirm with him

**Comment by woderchen** [comment]
yes, the user has not authorized the camera... thanks for your msg

**Comment by yannickl** [comment]
:+1:
