### ISSUE TITLE
How to hide the status bar

### ISSUE THREAD

**Issue by alibasta** [yannickl/QRCodeReader.swift#31]
Hi,

thanks for this great pod! I'm using your project for an iPhone app and I want to hide the status bar in the modally presented QR scanner view? Is there any way to hide the status bar in the QRCodeReaderViewController?

Thanks!

Best

Alex

**Comment by yannickl** [comment]
Hi, there is no provided method for this purpose. However I just update the project to allow you to subclass the `QRCodeViewController` class and the `viewWillAppear:`, `viewWillDisappear:` methods.
