### ISSUE TITLE
How to use TorchToggle and SwitchCameraButton

### ISSUE THREAD

**Issue by panagorn** [yannickl/QRCodeReader.swift#32]
Can you please give an example how to use TorchToggle and SwitchCameraButton? Thank you

**Comment by yannickl** [comment]
The example project activate by default the torch and camera switch buttons.

The only way to work with these buttons is via the initializer method:

```swift
init(cancelButtonTitle: String, coderReader: QRCodeReader, startScanningAtLoad: Bool, showSwitchCameraButton: Bool, showTorchButton: Bool)
```
