### ISSUE TITLE
UIViewController does not conform to protocol QRCodeReaderViewControllerDelegate

### ISSUE THREAD

**Issue by reshadf** [yannickl/QRCodeReader.swift#33]
Hi I have the error 
    
    UIViewController does not conform to protocol QRCodeReaderViewControllerDelegate

While I have implemented every required method 

    
    func reader(reader: QRCodeReaderViewController, didScanResult result: String) {
        self.dismissViewControllerAnimated(true, completion: { [unowned self] () -> Void in
            let alert = UIAlertController(title: "QRCodeReader", message: result, preferredStyle: .Alert)
            alert.addAction(UIAlertAction(title: "OK", style: .Cancel, handler: nil))
            
            self.presentViewController(alert, animated: true, completion: nil)
            })
    }
    
    func readerDidCancel(reader: QRCodeReaderViewController) {
        self.dismissViewControllerAnimated(true, completion: nil)
    }

What could be the problem here?

**Comment by yannickl** [comment]
Hi,

Have you asked your viewController to conform the protocol?

```swift
class YourViewController: UIViewController, QRCodeReaderViewControllerDelegate {
   // ...
}
```
