### ISSUE TITLE
Gab in the middle off the tabbar after scanning a ticket

### ISSUE THREAD

**Issue by tpcmedia777** [yannickl/QRCodeReader.swift#34]
Hi

i getting a gab in the middle off my tabbar after succesfull scanning a Ticket, if i press on the screen and wait for a few second i get my tabbar button back but with the text notification instead of "scanner"

Thanxz

**Comment by yannickl** [comment]
Hi,

can you put a screenshot please?

**Comment by tpcmedia777** [comment]
![image](https://cloud.githubusercontent.com/assets/15643644/11017303/2aaa4204-859b-11e5-8495-8e088e3e8aa4.jpg)
![image](https://cloud.githubusercontent.com/assets/15643644/11017304/2aaf0db6-859b-11e5-8f1c-a3de8dc3d210.jpg)
![image](https://cloud.githubusercontent.com/assets/15643644/11017305/2ab70020-859b-11e5-8eb0-6135f9a535e9.jpg)

**Comment by tpcmedia777** [comment]
Only if i scanned a ticket i get thus

**Comment by yannickl** [comment]
I just pushed a "fix", I don't know if it'll fix your problem. I need to see a bit of your code to know whether the problem comes from the lib.

**Comment by tpcmedia777** [comment]
didn't fixed it for me

Here is my Scanner code

class ScannerViewController: UIViewController, QRCodeReaderViewControllerDelegate {
    
    var scannedtickets = [NSManagedObject]()
    var alert = SCLAlertView()
    
    let managedObjectContext = (UIApplication.sharedApplication().delegate as! AppDelegate).managedObjectContext
    
    var frcontroller: NSFetchedResultsController = NSFetchedResultsController()
    
    struct status : JSONJoy {
        var error: Bool?
        var message: String?
        init() {
        }
        init(_ decoder: JSONDecoder) {
            error = decoder["error"].bool
            message = decoder["message"].string
        }
    }
    
    private func contentView(text: String) -> UIView {
        let view = UIView(frame: CGRect(x: 0, y: 50, width: 375, height: 64))
        view.autoresizingMask = [.FlexibleWidth, .FlexibleHeight]
        
        
        let label = UILabel(frame: view.bounds)
        label.frame.origin.x = 10
        label.frame.origin.y = 10
        label.frame.size.width -= label.frame.origin.x
        label.frame.size.height -= label.frame.origin.y
        
        label.autoresizingMask = [.FlexibleWidth, .FlexibleHeight]
        label.text = text
        label.numberOfLines = 2
        label.textColor = UIColor.whiteColor()
        view.addSubview(label)
        
        return view
    }
    
    
    lazy var reader = QRCodeReaderViewController(metadataObjectTypes: [AVMetadataObjectTypeQRCode])
    
    @IBAction func scanAction(sender: AnyObject) {
        if QRCodeReader.supportsMetadataObjectTypes() {
            reader.modalPresentationStyle = .FormSheet
            reader.delegate               = self
            
            reader.completionBlock = { (result: String?) in
                let evid =  NSUserDefaults.standardUserDefaults().objectForKey("eventid")
                
                let params = ["eventid": "\(evid!)", "qrcode":"\(result!)"]
                print(result)

                do {
                    let opt = try HTTP.POST("http://www.yourtickets.nl/api/app/checkticket", parameters: params)
                    opt.start { response in
                        //do things...
                        print(response.description)
                        let json = JSON(data: response.data)
                      
                        if json["error"] == true {
                            let mess = json["message"]
                            
                            dispatch_async(dispatch_get_main_queue(),{
                                
                                self.alert.showTitle(
                                    "Ongeldige Ticket", // Title of view
                                    subTitle: "\(mess)", // String of view
                                    duration: 3.0, // Duration to show before closing automatically, default: 0.0
                                    completeText: "Verder scannen", // Optional button value, default: ""
                                    style: .Error,// Styles - see below.
                                    colorStyle: 0xe74c3c,
                                    colorTextButton: 0xFFFFFF
                                ).setDismissBlock({ () -> Void in
                                    self.reader.startScanning()
                                })
                                
                                })

                        } else if json["error"] == false {
                            
                            self.title = "Notification"
                            
                            dispatch_after(dispatch_time(DISPATCH_TIME_NOW, Int64(1 * Double(NSEC_PER_SEC))), dispatch_get_main_queue()) {
                                let access = json["access"]
                                
                                if access == "granded" {
                            
                                    
                                    let mess =  json["message"]
                                    
                                        let qrid = json["ticket"]["id"].string!
                                       let klantnaams = json["ticket"]["klant_naam"].string!
                                       let ticketnaams = json["ticket"]["ticketnaam"].string!
                                       let geldigs = json["ticket"]["geldig"].string!
                                       let ticket_ids = json["ticket"]["ticket_id"].string!
                                       let eventids = json["ticket"]["eventid"].string!
                                       let emails = json["ticket"]["email"].string!
                                        let qrcodes = json["ticket"]["qrcontent"].string!
                                        
                                        self.createTickets(qrid,klantnaam: klantnaams,ticketnaam: ticketnaams,geldig: geldigs,ticket_id: ticket_ids,eventid: eventids,email: emails,qrcode: qrcodes)
                                    
                                    self.alert.showTitle(
                                        "Ticket Goedgekeurd", // Title of view
                                        subTitle: "\(mess)", // String of view
                                        duration: 3.0, // Duration to show before closing automatically, default: 0.0
                                        completeText: "Verder scannen", // Optional button value, default: ""
                                        style: .Success,// Styles - see below.
                                        colorStyle: 0x2ecc71,
                                        colorTextButton: 0xFFFFFF
                                        ).setDismissBlock({ () -> Void in
                                            self.reader.startScanning()
                                        })
                                      NSNotificationCenter.defaultCenter().postNotificationName("Updater", object: nil, userInfo: nil)
                                } else if access == "denied" {
                                    
                                    let mess =  json["message"]
                                    
                                    self.alert.showTitle(
                                        "Ticket Afgekeurd", // Title of view
                                        subTitle: "\(mess)", // String of view
                                        duration: 3.0, // Duration to show before closing automatically, default: 0.0
                                        completeText: "Verder scannen", // Optional button value, default: ""
                                        style: .Error,// Styles - see below.
                                        colorStyle: 0xe74c3c,
                                        colorTextButton: 0xFFFFFF
                                        ).setDismissBlock({ () -> Void in
                                            self.reader.startScanning()
                                        })

                                    
                                }
                             

                            
                            }
                          
                              /* self.savetickets("1",ticketnaam: "test",ticket_id: "2",event_id: "33",qrcontent: "32332-2-23",klant_naam:"sharlutci poeketi",geldig: "21-09-2016",email: "sbthugs@hotmail.com") */
                        }
                    }
                } catch let error {
                    print("got an error creating the request: \(error)")
                }
            }
            
            presentViewController(reader, animated: true, completion: nil)
        }
        else {
            let alert = UIAlertController(title: "Error", message: "QR Reader word niet ondersteund door uw apparaat", preferredStyle: .Alert)
            alert.addAction(UIAlertAction(title: "OK", style: .Cancel, handler: nil))
            
            presentViewController(alert, animated: true, completion: nil)
        }
    }
    
    // MARK: - QRCodeReader Delegate Methods
    
    func reader(reader: QRCodeReaderViewController, didScanResult result: String) {
        self.dismissViewControllerAnimated(true, completion: { [unowned self] () -> Void in
            let alert = UIAlertController(title: "QRCodeReader", message: result, preferredStyle: .Alert)
            alert.addAction(UIAlertAction(title: "OK", style: .Cancel, handler: nil))
            
            self.presentViewController(alert, animated: true, completion: nil)
            })
    }
    
    func readerDidCancel(reader: QRCodeReaderViewController) {
        self.dismissViewControllerAnimated(true, completion: nil)

    }

**Comment by yannickl** [comment]
I show nothing special with that. If you try with a very small project without all this boilerplate, is the problem occured?

**Comment by tpcmedia777** [comment]
i'll take a look

**Comment by PabloLerma** [comment]
@tpcmedia777 It's been more than half a year here but the problem was with the 
`self.title = "Notification"`
in one of your closures.
@yannickl I think we can close this issue.

**Comment by yannickl** [comment]
Yes you've right @PabloLerma! I didn't see this line. Thank you!
