### ISSUE TITLE
Customize appearance

### ISSUE THREAD

**Issue by mariselli** [yannickl/QRCodeReader.swift#35]
Hi, I've the top buttons (flash button and front camera button) that goes over status bar. There is any way to move the buttons a little bit down?
Another question, there is any way to customize the button cancel or customize the general view?

This is my view
![img_4097](https://cloud.githubusercontent.com/assets/1041289/10953065/4c843b5c-8346-11e5-8b06-f95227c11031.jpg)

**Comment by yannickl** [comment]
Hi,

I fix the issue with the buttons that overlap the status bar. :)

For the moment the `QRCodeViewController` class aims to provide a default/example display. However it should be interesting to allow users to customize it. If you have time you can handle this task, or I'll allow that in the future.

Thanks
