### ISSUE TITLE
Pods/QRCodeReader.swift: Is a directory

### ISSUE THREAD

**Issue by ymsheng** [yannickl/QRCodeReader.swift#36]
egrep: /Pods/Target Support Files/QRCodeReader.swift: Is a directory

WARNING

**Comment by yannickl** [comment]
Yes that's normal, There are only folder in the `/Pods/Target Support Files`. What is your issue?

**Comment by ymsheng** [comment]
your project name (QRCodeReader.swift) suffix with ".swift"; when xcode build the targe show warning message QRCodeReader.swift: Is a directory;  but .swift is swift file suffix. 

so how about change name to QRCodeReaderSwift ??

**Comment by yannickl** [comment]
Which version of Xcode are you using? I don't have any warnings?

I could change its name, but by creating a new podspec and deprecated the current one (http://stackoverflow.com/questions/28789807/how-to-rename-a-cocoapod). I'm afraid of changing it for the moment.

**Comment by ymsheng** [comment]
thanks for you reply, i'm using xcode 7.2 .

**Comment by FransGH** [comment]
This happens in combination with this xcode build script to generate #warnings in swift:

http://krakendev.io/blog/generating-warnings-in-xcode

**Comment by yannickl** [comment]
@FransGH Oh I see, thank you for the tip!

**Comment by yannickl** [comment]
I close this issue because nobody else has this issue.
