### ISSUE TITLE
Type of the scanned code when reader is set to read multiple metadataObjectTypes

### ISSUE THREAD

**Issue by Diphaze** [yannickl/QRCodeReader.swift#37]
Hi, 

First, thanks for your nice work :)

In my app, I need to read different types of codes, and depending on the type of the scanned code, I need to substring the resulting string code. And, I might have missed something but I did not managed to get the type of the scanned code read (_readableCodeObject.type).

For people who need to read different types of codes, would it be possible to add the type of the code actually read ? 

The problem is : the output will not result in a String? anymore...

**Comment by yannickl** [comment]
Hi,

This is a good idea. I never had this use case yet, but i think it's really useful. 

Yes it'll change the delegate method signature but I'll update the major version of the lib by the same time.

**Comment by Diphaze** [comment]
Hi, 

Thanks for your quick answer.
I pulled the changes I made, in case it could help/save time.

**Comment by yannickl** [comment]
Thank you! I merged it. :+1: 

I'll upgrade the version of the pod in the next few days because I have some change to do before.

**Comment by Diphaze** [comment]
You're very welcome ! Glad you merged it since I'm new to GitHub and it was actually my first pull request ;-)
