### ISSUE TITLE
any update to (Xcode 7.1 Swift 2.1)

### ISSUE THREAD

**Issue by rjjohnpatrickcruz** [yannickl/QRCodeReader.swift#39]
Hi @yannickl ,

Your library was so great, I'm using it in my applications. Just want to know if are you considering to update this in the latest Xcode and Swift versions ?

Thanks.

**Comment by yannickl** [comment]
Hi,

The project is already updated to Swift 2.1. I'm using Xcode 7.2 and everything works great. Have you the last version of the project?

Best

**Comment by rjjohnpatrickcruz** [comment]
Hi @yannickl,

Yup, my bad..

Thanks.

**Comment by rjjohnpatrickcruz** [comment]
Hi @yannickl,

Any help I'm still getting this error.. Please see my screenshots.

<img width="746" alt="screen shot 2016-01-04 at 8 48 18 am" src="https://cloud.githubusercontent.com/assets/5118009/12081927/d9244852-b2c3-11e5-9544-53953879f5f3.png">

Im getting that error even if I already have the delegates.
<img width="424" alt="screen shot 2016-01-04 at 8 48 39 am" src="https://cloud.githubusercontent.com/assets/5118009/12081939/028dbe62-b2c4-11e5-83e0-5891ef35a03e.png">

And because of that Im also getting this error.
<img width="746" alt="screen shot 2016-01-04 at 8 48 27 am" src="https://cloud.githubusercontent.com/assets/5118009/12081942/10797160-b2c4-11e5-8c5e-fa02e5e64958.png">

Hope for kind help!

Thanks.
