### ISSUE TITLE
Takes time in scanning

### ISSUE THREAD

**Issue by sumitjain7** [yannickl/QRCodeReader.swift#4]
I used the same kind of code in my application. It takes some time in reading the code. What could be the reason and its solution. Do I need to use ZXing kind of third party library for this?

**Comment by yannickl** [comment]
Hi,

With what kind of device do you test (iphone/ipad/ipod, version number, etc...)?

It's slow how? Have you tried to use the instrument to check what is wrong? Have you some code to share?

**Comment by sumitjain7** [comment]
I tested it on all devices. sometimes it detects QR code very fast. and some times it takes time. My client said that some of appstore app scans immediately. what shall i do? 
Moreover how could I share my class file here?

**Comment by yannickl** [comment]
You can use a gist file or just copy the code here.

The `QRCodeReader` is based on the AVFoundation so it uses the Apple algorithm. May be it is an issue with the autofocus?

**Comment by sumitjain7** [comment]
let captureDevice:AVCaptureDevice = AVCaptureDevice.defaultDeviceWithMediaType(AVMediaTypeVideo)
        
        captureDevice.lockForConfiguration(nil);
        captureDevice.whiteBalanceMode = AVCaptureWhiteBalanceMode.ContinuousAutoWhiteBalance;
        captureDevice.focusMode = AVCaptureFocusMode.ContinuousAutoFocus;
        captureDevice.unlockForConfiguration();
        
        // Get an instance of the AVCaptureDeviceInput class using the previous device object.
        var error:NSError?
        let input: AnyObject! = AVCaptureDeviceInput.deviceInputWithDevice(captureDevice, error: &error)
        
        if (error != nil) {
            // If any error occurs, simply log the description of it and don't continue any more.
            //  println("\(error?.localizedDescription)")
            return
        }
        
        
        // Initialize the captureSession object.
        captureSession = AVCaptureSession()
        // Set the input device on the capture session.
        captureSession?.addInput(input as AVCaptureInput)
        
        // Initialize a AVCaptureMetadataOutput object and set it as the output device to the capture session.
        let captureMetadataOutput = AVCaptureMetadataOutput()
        captureSession?.addOutput(captureMetadataOutput)
        
        // Set delegate and use the default dispatch queue to execute the call back
        captureMetadataOutput.setMetadataObjectsDelegate(self, queue: dispatch_get_main_queue())
        captureMetadataOutput.metadataObjectTypes = supportedBarCodes
        
        // Initialize the video preview layer and add it as a sublayer to the viewPreview view's layer.
        videoPreviewLayer = AVCaptureVideoPreviewLayer(session: captureSession)
        videoPreviewLayer?.videoGravity = AVLayerVideoGravityResizeAspectFill;
        videoPreviewLayer?.frame = cameraPreviewView.layer.bounds;

**Comment by sumitjain7** [comment]
This was the basic code. There is a specific qr code to which my app is not reading. but other qr code scanning apps are reading it.(zxing app on appstore is reading it efficiently).
Is there something to increase efficiency etc?

**Comment by yannickl** [comment]
By watching your code I don't see anything. Can I have the QRCode to make the test here?

**Comment by sumitjain7** [comment]
![13092_1414357736_coupon84500_2_i_84501](https://cloud.githubusercontent.com/assets/2204075/6488946/cbbd38b6-c2c0-11e4-9b79-9c0a19399015.png)


The above coloured image qr code is not detectable from my code. But a black and white print out of this image is readable. But the apps on appstore can read it easily.

**Comment by yannickl** [comment]
Indeed it does not work, even if I zoom or if I change the color. This may be a bug from Apple. You should report them by adding a new radar with this image.

**Comment by sumitjain7** [comment]
If I change the background color from red to white.. It reads is instantly.
How to report a bug to apple?

**Comment by yannickl** [comment]
If i change the color here it does no effect.

Here is the link for the Apple bug report: https://bugreport.apple.com/

**Comment by sumitjain7** [comment]
Have you used Zxing library? I downloaded "Barcodes"  app from appstore. Its based on Zxing library. Its working very fine.

**Comment by yannickl** [comment]
Yes I already used Zxing but it uses its own algorithm, its not based on the `AVFoundation`.

**Comment by sumitjain7** [comment]
Can you help me in integrating this library for ios swift. I am new to ios develpment.

**Comment by yannickl** [comment]
With Cocoapod it does not work?

**Comment by sumitjain7** [comment]
I have not used cocoapod before.
