### ISSUE TITLE
supportsMetadataObjectTypes crash

### ISSUE THREAD

**Issue by gGololicic** [yannickl/QRCodeReader.swift#40]
My app is crashing on some specific devices in production. This is the line where it crashes.
QRCodeReader: function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Dead> of static QRCodeReader.QRCodeReader.supportsMetadataObjectTypes (QRCodeReader.QRCodeReader.Type)([Swift.String]?) -> Swift.Bool + 2408

**Comment by yannickl** [comment]
Thank you for the precision. I'll investigate this.

**Comment by Place1** [comment]
Hey, I was having this issue as well but it was because I hadn't set the `Privacy - Camera Usage Description` property in the `Info.plist`

[small guide](http://useyourloaf.com/blog/privacy-settings-in-ios-10/)

**Comment by hananahmad** [comment]
Hi ,
My app is crashing when app asks for permission of camera usage after tap on settings it will got to the settings and when I have enable the camera permissions app kills with this message in console "Terminated due to signal 9"
