### ISSUE TITLE
Differentiate between stop scanning and stop running

### ISSUE THREAD

**Issue by sdduursma** [yannickl/QRCodeReader.swift#41]
I would like to be able to differentiate between stop scanning and stop running.

Currently `QRCodeReader` calls `stopScanning` when a QR code is found. `stopScanning` calls `stopRunning` on the `AVCaptureSession` which stops the video preview. This is undesirable for us as the 'QR screen' is not dismissed when a QR code is found and the sudden halting of the video preview is not a smooth user experience.

**Comment by yannickl** [comment]
Is, like in the last commit, a `stopScanningWhenCodeIsFound` property is sufficient for you or do you need more control?

**Comment by sdduursma** [comment]
@yannickl Yes that provides sufficient control. Thanks!
