### ISSUE TITLE
codeReader: QRCodeReader access modifier should be public

### ISSUE THREAD

**Issue by fraserscottmorrison** [yannickl/QRCodeReader.swift#43]
Related to issue 23 https://github.com/yannickl/QRCodeReader.swift/issues/23

I want to use your reader but need to provide my own UI overlay so I need to insert codeReader.previewLayer onto my own view.

But QRCodeReaderViewController's codeReader uses the default access modifier which is 'internal'. Could you change it to 'public' so that we can access it

**Comment by yannickl** [comment]
Ok I'll llook at the best way to customize the overlay view in the next few day. Or if you have time, you're welcome. :)

**Comment by fraserscottmorrison** [comment]
Ive figured out how to use a custom overlay while hiding the default one

firstly, the codeReader needs to be made public

then

        self.addChildViewController(self.reader)
        self.view.addSubview(self.reader.view)
        self.reader.view.hidden = true
        
        // use SnapKit to add constraints to subview
        self.reader.view.snp_makeConstraints { (make) -> Void in
            make.edges.equalTo(self.view).inset(UIEdgeInsetsMake(0, 0, 0, 0))
        }
        
        self.reader.codeReader.previewLayer.removeFromSuperlayer()
        self.view.layer.insertSublayer(self.reader.codeReader.previewLayer, atIndex: 0)

Note, Im not showing this modally. The code is in a custom View Controller

**Comment by yannickl** [comment]
If you are not using it modally I think the best solution is to create your own view. Here this is almost the same thing.

You can create the QRCodeReader object and insert the previewLayer directly.

**Comment by yannickl** [comment]
With the last version the `qrcodeReader` property is now public. :+1:
