### ISSUE TITLE
handle vcard

### ISSUE THREAD

**Issue by happiehappie** [yannickl/QRCodeReader.swift#46]
If I scanned a vcard, how am I able to automatically create a contact based on the vcard, or is there any way for me to workaround?

**Comment by yannickl** [comment]
You can use some another external lib like `SwiftAddressBook`: https://github.com/SocialbitGmbH/SwiftAddressBook/issues/41. The `QRCodeReader.swift` is only focused on the scan and not the value processing.

**Comment by happiehappie** [comment]
But the question is how do I know if I get a vcard or a web page etc, cause QRCodeReaderResult only prints the entire value else type org.iso.QRCode, which is both just a string
Sorry if this is answered elsewhere

**Comment by yannickl** [comment]
Ah ok, the type returned by the result is the type of the code:

```
"org.gs1.UPC-E",
"org.iso.Code39",
"org.iso.Code39Mod43",
"org.gs1.EAN-13",
"org.gs1.EAN-8",
"com.intermec.Code93",
"org.iso.Code128",
"org.iso.PDF417",
"org.iso.QRCode",
"org.iso.Aztec"
```

Indeed the QRCodeReader can read in reality more code type than QRCodeReader.

You'll need to determine yourself the type of the value that you scan.
