### ISSUE TITLE
Cannot prevent previewLayer from changing orientation

### ISSUE THREAD

**Issue by fraserscottmorrison** [yannickl/QRCodeReader.swift#48]
My app only supports Portrait mode but when the phone is put into landscape, the previewLayer is rotated

In `QRCodeReaderViewController.orientationDidChanged(notification: NSNotification)` you call `supportedInterfaceOrientations()` but because QRCodeReaderViewController doesn't declare `override public func supportedInterfaceOrientations() -> UIInterfaceOrientationMask`, the default results are returned (Portrait and Landscape).

Ive had to modify QRCodeReaderViewController and insert this to prevent rotation
`override public func supportedInterfaceOrientations() -> UIInterfaceOrientationMask {
        return [.Portrait]
    }
`

Perhaps you could have a delegate call to get the correct supportedInterfaceOrientations or get them from the parent view controller?

**Comment by yannickl** [comment]
Yes it would be a good idea. I don't have time for the moment so if you want add a pull request, you are welcome!
