### ISSUE TITLE
Focus

### ISSUE THREAD

**Issue by jerometonnelier** [yannickl/QRCodeReader.swift#5]
Often with small codes, the scanner is not able to focus properly. Is there a way to add a "tap to focus" behavior on the AVCaptureView?

**Comment by yannickl** [comment]
The only way for the moment is to subclass the `QRCodeReader` and the corresponding view controller.

But this is a good feature to add for a next release.

**Comment by jerometonnelier** [comment]
I'll upload my subclasses tomorrow :-)

---Sent from Boxer | http://getboxer.com

On 4 mars 2015 17:29:28 UTC+1, Yannick Loriot <notifications@github.com> wrote:The only way for the moment is to subclass the QRCodeReader  and the corresponding view controller.  But this is a good feature to add for a next release.  —Reply to this email directly or view it on GitHub.

**Comment by davidjaystrauss** [comment]
Did you ever get this to work? Can I ask how?
