### ISSUE TITLE
Update swift3 branch for Xcode 8.0 ß6

### ISSUE THREAD

**Issue by dpcrook** [yannickl/QRCodeReader.swift#51]
I tried the `swift3` branch today, and encountered many issues where it would not compile under Xcode 8.0 ß6 / Swift 3.0 / iOS 10

I was able to make the updates to get Framework compiling/working in Swift 3. I created this issue so to track this and will generate a PR.

**Comment by yannickl** [comment]
Thank you for your help! I'm going to merge it.
