### ISSUE TITLE
stopped when running on simulator 

### ISSUE THREAD

**Issue by cagricolak** [yannickl/QRCodeReader.swift#53]
its give me this error on Xcode 7.3.1 swift 2.2;

> fatal error: unexpectedly found nil while unwrapping an Optional value

when i compile and run my project give it this error, i don't write in viewdidload method for calling scan method, actually IBActionButton triggered for scan.

note: this error occurred in this week, 23-28 August 2016.

**Comment by yannickl** [comment]
Without more context (sample code, example, stack trace) it will be difficult to help you. Here the error just say you are trying to use an `Optional` which is nil.

**Comment by cagricolak** [comment]
<img width="1024" alt="ekran resmi 2016-08-30 12 40 25" src="https://cloud.githubusercontent.com/assets/11461422/18084274/3ca40bea-6eaf-11e6-9216-208ac1faf333.png">
this is your own class, and this 
<img width="723" alt="ekran resmi 2016-08-30 12 44 11" src="https://cloud.githubusercontent.com/assets/11461422/18084336/80d1d9fa-6eaf-11e6-94b1-ad73a29759f2.png"> is my class. you can see i didn't call in my viewDidload method but its occurred when i compile and run on simulator.

**Comment by cagricolak** [comment]
i catch it, i change var to lazy var its fixed.
` lazy var qrKodOkuyucuVC = QRCodeReaderViewController(metadataObjectTypes: [AVMetadataObjectTypeQRCode])` i missed lazy word before using your class, sorry about that.
