### ISSUE TITLE
Cant install via cocoapods

### ISSUE THREAD

**Issue by yerassyl** [yannickl/QRCodeReader.swift#55]
Added pod into podfile as were shown.
pod 'QRCodeReader.swift', '~> 6.1.0'

when run: pod install get this error:
None of your spec sources contain a spec satisfying the dependency: `QRCodeReader.swift (~> 6.1.0)`.

**Comment by yannickl** [comment]
It may be a cache problem of Cocoapods. Have you tried to clean it?

```
$ pod cache clean QRCodeReader.swift
$ pod install
```

**Comment by yerassyl** [comment]
I got this message: [!] No cache for pod named QRCodeReader.swift found

**Comment by yerassyl** [comment]
BTW I will post full error message:
[!] Unable to satisfy the following requirements:

- `QRCodeReader.swift (~> 6.1.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `QRCodeReader.swift (~> 6.1.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by yannickl** [comment]
Is the `pod repo update` worked?

**Comment by yerassyl** [comment]
Yep, it helped, thanks.
