### ISSUE TITLE
Using CocoaPods 7.0.0 install Xcode 8 insists migrating to Swift 3

### ISSUE THREAD

**Issue by andrewsage** [yannickl/QRCodeReader.swift#57]
I've installed using CocoaPods 7.0.0.
Xcode 8 wants to migrate QRCodeReader to Swift 3 but then won't let me as some of the files are locked as it is a CocoaPod.
If I say no to Swift 3 migration then it won't compile my code as it doesn't think QRCodeReader exists.

**Comment by yannickl** [comment]
Have you unchecked the pods during the migration?

Here an example screenshot:

<img width="731" alt="screen shot 2016-09-14 at 15 01 49" src="https://cloud.githubusercontent.com/assets/798235/18513104/47505d30-7a8c-11e6-99a2-5c19634ff47c.png">

**Comment by andrewsage** [comment]
Yes I did uncheck them.
It was then it gave the error about being Swift 1 code.

I managed to get it to work by removing the Pod from my Podfile to uninstall it and then added it back in again. After a reboot it worked so I think Xcode may have just become confused.

**Comment by yannickl** [comment]
Yes, may be. Xcode is not perfect, and unfortunately the migration tool is not really reliable. So everything works now? Can I close the issue?

**Comment by yannickl** [comment]
No probs, you're welcome. 👍
