### ISSUE TITLE
Type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by datthanhvu98** [yannickl/QRCodeReader.swift#58]
Build Failed !!!
Hi guy , in QRCodeReader.swift ->  return .defaultDevice(withDeviceType: .builtInWideAngleCamera, mediaType: AVMediaTypeVideo, position: .front) failed !!!

**Comment by yannickl** [comment]
That's really strange, it works fine for me. Which Xcode version have you?

Btw I released a new version (7.0.1) which should fix it.

**Comment by datthanhvu** [comment]
Thank you !

**Comment by datthanhvu** [comment]
xcode 8 beta but download version 7.0.1 -> build failed . "Extra argument "withDeviceType"in call and "mediaType"

**Comment by yannickl** [comment]
The v7.x version is written in Swift 3 so it does not work with Xcode 7 which only support Swift 2.2.

If you work with Xcode 7 you should use the QRCodeReader.swift v6.x.

**Comment by datthanhvu** [comment]
No i use xcode 8 beta , isnt wrong ?

Vào Thứ Năm, ngày 15 tháng 9 năm 2016, Yannick Loriot <
notifications@github.com> đã viết:

**Comment by yannickl** [comment]
I didn't test with Xcode beta (which version?). You should download the last version of Xcode 8 with the final version of Swift 3.

**Comment by datthanhvu** [comment]
Okie i will dowload the release versiom , thank for reply

Vào Thứ Năm, ngày 15 tháng 9 năm 2016, Yannick Loriot <
notifications@github.com> đã viết:
