### ISSUE TITLE
setMetadataObjectTypes

### ISSUE THREAD

**Issue by theGrimm** [yannickl/QRCodeReader.swift#6]
Hey, i get this Error Message when starting your Example Project on Xcode 6.1.1 

QRCodeReader.swift[70320:1605607] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureMetadataOutput setMetadataObjectTypes:] - unsupported type found.  Use -availableMetadataObjectTypes.'

thanks for your help

**Comment by yannickl** [comment]
Hi,

I update the project (and the example) to check whether the reader is available.
If you test it with the simulator it does not work because it has no camera for example.

**Comment by theGrimm** [comment]
ok thanks alot :+1:
