### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by jvmk** [yannickl/QRCodeReader.swift#60]
When installing using CocoaPods, xcode offers to convert to Swift 3. I tried pointing to the tip of the master like so, but without any luck:
pod 'QRCodeReader.swift', :git => 'https://github.com/yannickl/QRCodeReader.swift' #point to master to get swift 3 version.

Browsing the files here on github, it seems they do not comply with the Swift 3 syntax that xcode 8 enforces (e.g. replacing public with open, private with fileprivate).

**Comment by yannickl** [comment]
The v7.x is Swift 3 / Xcode 8 compatible (the master). Which version of Cocoapods are you using?

To support Swift3 and Xcode 8 with Cocoapods you have to the `1.1.0.rc.2` installed.

**Comment by jvmk** [comment]
@yannickl thanks for the swift (pun intended) reply :).

I'm using CocoaPods 1.0.1. I have successfully used other Swift 3 pods, so I wonder why this particular one would require me to update to a rc version...?

**Comment by yannickl** [comment]
@jvmk Unfortunately I have no answer. I had a lot of different issues with Cocoapods 1.0.1 and 1.1.0 betas (https://github.com/CocoaPods/CocoaPods/issues/5864) but it seems disparate.

With Xcode8 you need to specify the `SWIFT_VERSION` for each lib and targets and Cocoapods (`1.1.0.rc.2` and over) provides a `.swift-version` file to do so. I think some libraries are almost the same in Swift 2.3 and Swift 3 and Xcode can deals with.

By waiting for the Cocoapods 1.1.0, you can manually set the `SWIFT_VERSION` for the problematic pods?

**Comment by jvmk** [comment]
@yannickl Interesting, updating to the 1.1.0.rc.2 did indeed make xcode accept QRCodeReader.swift as Swift 3. Thank you for the tip -- looking forward to using your library :)

**Comment by syafiqsinwan** [comment]
Hai. Can i know on how to use this QRCodeReader with full screen instead of the particular size. I've try to find on adding the size but it only effect to the cancel button, switch camera button. I need to know on how to use it as fullscreen. Thank you.
