### ISSUE TITLE
v6.2.0 version not compiling  with Swift 2.3 and Xcode 8

### ISSUE THREAD

**Issue by Zkriya** [yannickl/QRCodeReader.swift#61]
is it compatible with swift 2.3 in iOS 8.0 ?

**Comment by yannickl** [comment]
Hi,

Unfortunately no. You should use the `swift2.3` branch instead.

```
pod 'QRCodeReader.swift', :git => 'https://github.com/yannickl/QRCodeReader.swift', :branch => 'swift2.3'
```

**Comment by giofid** [comment]
Hi,
perhaps it would be best if you change README.md in the [swift2.3](https://github.com/yannickl/QRCodeReader.swift/blob/swift2.3/README.md) branch to reflect this problem.

**Comment by yannickl** [comment]
@giofid  You're right. I've just updated it. 👍
