### ISSUE TITLE
Unable to read specific barcode with type Code-128

### ISSUE THREAD

**Issue by wajahatch888** [yannickl/QRCodeReader.swift#62]
Hello Guys,
I am using this barcode reader and it seems very good but i am facing one issue with CODE-128 type. I am attaching screenshot with highlighting two different barcodes but with same type CODE-128. The green one is very easily readable within a second but  i am facing difficulty with red one. It takes a lot of time to read with 90% failure rate.I am using version 6.0 and i need very urgent help. Your help will be appreciated. Thanks
![img_6322](https://cloud.githubusercontent.com/assets/5916442/19189176/e4aeb4fc-8caf-11e6-8e74-556feff2739a.JPG)

**Comment by yannickl** [comment]
I have the same problem with this image.

The library is based on the Apple's `AVFoundation` so if there are issues to read code should open a bug report (https://bugreport.apple.com).

**Comment by wajahatch888** [comment]
Thanks @yannickl for the reply.
Can you please suggest me any alternative which can read that barcode? i need to integrate this feature in project very badly.

**Comment by yannickl** [comment]
Maybe [ZBar](http://zbar.sourceforge.net/iphone/index.html) but it's much harder to integrate in an iOS project.
