### ISSUE TITLE
Access Camera Facing Feature Request

### ISSUE THREAD

**Issue by cody1024d** [yannickl/QRCodeReader.swift#67]
In my use case, I would like to be able to access which camera is being used.  Further, to be able to be notified (via the delegate?) when the camera is switched.

The use case here is so that I can store which camera the user uses to capture an image, and then persist that for future use.

Is this something that I can PR, and add in in a relatively quick time frame?  I have need for it in a production application.

**Comment by yannickl** [comment]
Yes of course, you can propose this feature. Just make a PR and I'll review and integrate it.

**Comment by cody1024d** [comment]
Ok, cool.  Working on it now.  This may be a silly question, but I've never worked with a library in which there wasn't XCode project files, etc. within them.  How would I go about opening this project to make the necessary changes?
