### ISSUE TITLE
Scanning multiple QRs at once

### ISSUE THREAD

**Issue by BasThomas** [yannickl/QRCodeReader.swift#69]
I am not sure if this is really an issue, but when using this, I noticed you can easily scan multiple QRs at once. This means, when having the `dismiss(animated: true)` in your `didScanResult`, you can end up dismissing multiple view controllers (instead of only the `QRCodeReaderViewController`).

Might be useful to add a warning to the README for this?

**Comment by yannickl** [comment]
Yes indeed, you should first call `reader.stopScanning()` to stop the scan. I'll add this into the README example. Thank you!
