### ISSUE TITLE
submit to app Store 

### ISSUE THREAD

**Issue by embassem** [yannickl/QRCodeReader.swift#71]
i guess you need to app a key to info.plist for Privacy - Media Library Usage Description
app Binary was invalid till i add  to my info.plist  the Error was missing this Key "NSPhotoLibraryUsageDescription"

please put a hint in readme file as it required from iOS 10

**Comment by yannickl** [comment]
Hi,

Are you sure it came from the `QRCodeReader.swift` library? You don't use another lib that might use the media library?

If you go to the Settings > QRCodeReaderExample you will see that the only permission the lib asks is the camera. We do not need the media library.

**Comment by embassem** [comment]
and my app didn't  have a permissionfor Media , and i  didn't ask for it  ,but i think that using Camera will need this Key with Privacy for camera i plist

**Comment by yannickl** [comment]
Ok, thank you. I'll update this later.
