### ISSUE TITLE
Change Scanner Border Design

### ISSUE THREAD

**Issue by patikzetrixweb1234** [yannickl/QRCodeReader.swift#72]
is this possible to change scanner view?

**Comment by yannickl** [comment]
Hi, unfortunately not for the moment, but this is in the roadmap (I don't know when it'll be released yet).

**Comment by patikzetrixweb1234** [comment]
i need to change in just border. i need only for corner in scanner view.

**Comment by yannickl** [comment]
I've updated the project you can now create your own view and customize it as you want. Just update the project to the v7.2.0.
