### ISSUE TITLE
Options to "Hide rectangular guide" view or "Zoom"

### ISSUE THREAD

**Issue by RickyPark** [yannickl/QRCodeReader.swift#74]
Hi,
First of all, thanks for great open source! =)

I'm considering using QRCodeReader.swift, but I thought it would be better if I have **options to hide rectangular guide view (`ReaderOverlayView` object) or zoom**. The option to hide rectangular guide view doesn't look so complicated though the structure seems to be changed. The options to support zooming feature is simpler, but IMO it should be checked why no apps support zooming feature. (I tried to add zooming feature, and it just works well. I thought about it, but don't have any idea about the reason not to support it so far.)

I tried to test about these, so I could make pull requests but I'd like to know your idea about these first. Thanks for reading my issue!

Regards,

**Comment by yannickl** [comment]
Hi @RickyPark,

If you want add these features you are welcome. For the zoom option, apps don't needs it because the zoom is numeric and so it doesn't improve the scan (expect with the last iPhone).

Regards,

Yannick

**Comment by RickyPark** [comment]
Thanks for reply @yannickl :)

I thought zooming helps me to read qrcode images far from me like this test (gif below), but it might be different.. anyway, I'd like to get ready for pull request for guide view.

![10 -26-2016 20-51-20](https://cloud.githubusercontent.com/assets/2542436/19724983/ffac6c50-9bbd-11e6-8b3d-4a8dba6573d0.gif)

Regards,

Ricky

**Comment by yannickl** [comment]
It looks nice! +1

**Comment by sunsunai** [comment]
How we can implement this zoom feature ? And how I can change the rectangular guide view with another view for example UIImageView ?

@RickyPark Can you help me sir ?

**Comment by RickyPark** [comment]
Sorry for late reply!

It might take a little more time, so I just copied&pasted zoom code. You should use `videoMaxZoomFactor` instead of `4.0`. (You can also add slider to zoom/release.)


```
//QRCodeReaderViewController.swift
public override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
        do {
            print("lock")
            try self.codeReader.defaultDevice.lockForConfiguration()
            self.codeReader.defaultDevice.ramp(toVideoZoomFactor: 4.0, withRate: 0.8)
            self.codeReader.defaultDevice.unlockForConfiguration()
            print("unlock")
        } catch {
            print("oops?")
        }
}
```

**Comment by RickyPark** [comment]
The pull request for hiding guide view is merged. (https://github.com/yannickl/QRCodeReader.swift/pull/80)
