### ISSUE TITLE
Redesign the default scan view 

### ISSUE THREAD

**Issue by yannickl** [yannickl/QRCodeReader.swift#76]
It would be great if someone could update the scan view in order to make it more beautiful and usable.

If you wan contribute don't hesitate to post your own views here!

**Comment by xinsight** [comment]
After some experimentation, I don't think the dashed line box is required as the QR code can be anywhere in the screen and it will be detected. (I usually can't even get the code to the middle of the screen before it's detected!)

**Comment by hanguyen221** [comment]
You could refer to my answer @ https://github.com/yannickl/QRCodeReader.swift/issues/83. Hope it works.
