### ISSUE TITLE
Can I pick a image from library photo and scan it ?

### ISSUE THREAD

**Issue by sunsunai** [yannickl/QRCodeReader.swift#78]
I want to pick a image about barcode or qr-code in my library photo and then scan it. How I can do that if can ?

**Comment by yannickl** [comment]
@sunsunai unfortunately no. But if you want add this feature you're welcome to make a pull request.

**Comment by sunsunai** [comment]
Thank for quick reply. 👍

**Comment by harkmall** [comment]
@sunsunai I implemented this on my fork: [https://github.com/harkmall/QRCodeReader.swift](https://github.com/harkmall/QRCodeReader.swift)
You can have a look. It only works for QRCodes cause I'm using CoreImage to analyze the image. 

@yannickl you can also look at it and I can make a PR if if looks ok
