### ISSUE TITLE
swift 3 incompatible

### ISSUE THREAD

**Issue by maslyankov** [yannickl/QRCodeReader.swift#79]
"The target “QRCodeReader.swift” contains source code developed with an earlier version of Swift.

Choose “Convert” to update the source code in this target to the latest SDKs. You will be given the choice to use Swift 2.3 syntax or update to Swift 3.

This action can be performed later using “Convert to Current Swift Syntax” in the Edit menu."
for pod 'QRCodeReader.swift', '~> 7.2.0'

**Comment by yannickl** [comment]
The library is Swift3 compatible. How do you import the lib into your project?

**Comment by maslyankov** [comment]
As stated in the Readme file. I add: pod 'QrCodeReader.swift', '~> 7.2.0'
And then pod install
Open the xcworkspace and then the error comes up

**Comment by yannickl** [comment]
Which version of Cocoapods are you using?

**Comment by maslyankov** [comment]
1.0.1

**Comment by yannickl** [comment]
Ok, so update you Cocoapods version and tell me if your issue persists please?

**Comment by maslyankov** [comment]
Yes, it works now. Sorry for bothering you! Thank you for the great software and for the fast response!!!

**Comment by yannickl** [comment]
@maslyankov you're welcome. ;)
