### ISSUE TITLE
I am trying to use CocoaPods

### ISSUE THREAD

**Issue by gambaldia** [yannickl/QRCodeReader.swift#8]
I am trying to use CocoaPods for the first time. First impression is VERY GOOD.

But it gives some errors.

Warning: no rule to process file '/Users/xxxx/x/Pods/QRCodeReader.swift/README.md' of type net.daringfireball.markdown for architecture i386

XCODE thinks README.md should be compiled but he does not know how to.
Maybe it is caused by CocoaPads, but I think it is better to mention in the manual at "Installation" area to remove README.md from "Build Phases->Compile Sources" in the project file.
Unless this problem is happening only on me.

Hiro

**Comment by yannickl** [comment]
Hi, 

I have no problem with CocoaPods. Have you installed the 0.36 pre release version?

```[sudo] gem install cocoapods --pre```

**Comment by gambaldia** [comment]
I updated to : 0.36.0.rc.1

Then it gives an error so I added one line in Podfile.
use_frameworks!

Then pod install succeeded.

But the linker gives an error:
ld: framework not found QRCodeReader
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Framework not found QRCodeReader

I will get back to you after a bit more research about this.

Hiro

**Comment by datomnurdin** [comment]
You need to use . xcworkspace instead . xcodeproj.

**Comment by jlubeck** [comment]
I'm actually having all kinds of trouble while using CocoaPods. 
Check out all this problems inside the QRCodeReader framework:
http://prntscr.com/7pwwna

**Comment by jlubeck** [comment]
I tried using the latest commit in my PodFile:

pod 'QRCodeReader.swift', :git => 'https://github.com/yannickl/QRCodeReader.swift.git', :commit => '1fad101e6fc5f8beccd1814ee52140b0c96cb199'

And that fixed most of the problems, but there are still 2 in there that make the project unable to compile:
http://prntscr.com/7px0a9

**Comment by yannickl** [comment]
@jlubeck I just move the last 3 commits (including the `1fad101e6fc5f8beccd1814ee52140b0c96cb199`) into the `swift2` branch. Are you using Xcode7? I'll take a look to fix the prob on this branch.

**Comment by jlubeck** [comment]
Yup, xcode7
