### ISSUE TITLE
OverlayView and rotation

### ISSUE THREAD

**Issue by giacgbj** [yannickl/QRCodeReader.swift#89]
If you rotate the device after having started the acquisition the overlayView is not updated. 
You can test it using your own example.

**Comment by yannickl** [comment]
Sorry for the late, I'm really busy for the moment. If you have the time and the motivation, you can contribute. Otherwise I'll see later when I'all find time.

**Comment by acrespo** [comment]
This should be closed, now that #91 has been merged
