### ISSUE TITLE
Setting "reader" property after Xcode 8.3 (Swift 3.1) update

### ISSUE THREAD

**Issue by petkotodorov** [yannickl/QRCodeReader.swift#92]
<img width="1074" alt="screen shot 2017-03-28 at 3 17 57 pm" src="https://cloud.githubusercontent.com/assets/13046545/24407062/0bbdebde-13ca-11e7-97ee-54f179a4514a.png">

**lazy var initialization from the example should be replaced with this code, in order to avoid error**

`lazy var readerVC: QRCodeReaderViewController = {
        let builder = QRCodeReaderViewControllerBuilder {
            $0.reader = QRCodeReader(metadataObjectTypes: [AVMetadataObjectTypeQRCode], captureDevicePosition: .back)
        }
        return QRCodeReaderViewController(builder: builder)
    } ()`

**Comment by fraserscottmorrison** [comment]
+1

**Comment by 12789** [comment]
@petkotodorov Thanks

**Comment by petkotodorov** [comment]
I created pull request for this issue

**Comment by yannickl** [comment]
The library has been updated to the v7.4.0 which now supports Swift 3.1 thanks to @petkotodorov! Thank you!

**Comment by peihsendoyle** [comment]
is this issue really resolved? I'm still in stuck with this.
pod 'QRCodeReader.swift', ~> '7.4.0'

<img width="1185" alt="screen shot 2017-04-16 at 9 01 22 am" src="https://cloud.githubusercontent.com/assets/7514128/25068101/4b0d4da8-2283-11e7-8608-77d3a02d1b93.png">

**Comment by yannickl** [comment]
@peihsendoyle 

Yes it works, but Swift 3.1 has break the previous `QRCodeReaderViewController` lazy initialisation. Now you should init it like that:

```swift
lazy var readerVC: QRCodeReaderViewController = {
   let builder = QRCodeReaderViewControllerBuilder {
      $0.reader = QRCodeReader(metadataObjectTypes: [AVMetadataObjectTypeQRCode], captureDevicePosition: .back)
   }

   return QRCodeReaderViewController(builder: builder)
} ()
```

**Comment by peihsendoyle** [comment]
Many thanks, @yannickl. We could close this issue right now.
