### ISSUE TITLE
Warnings on Latest Xcode 8.3

### ISSUE THREAD

**Issue by mwaqasbhati** [yannickl/QRCodeReader.swift#96]
I am getting these warnings when I did try to build my project with latest xcode 8.3. I am attaching the screenshot.

<img width="469" alt="screen shot 2017-04-26 at 2 57 43 pm" src="https://cloud.githubusercontent.com/assets/8677149/25431244/d46b5012-2a90-11e7-8359-92083d44a210.png">

**Comment by yannickl** [comment]
Hi @mwaqasbhati,

Have you the last version? It should be fixed.

**Comment by mwaqasbhati** [comment]
sorry I just update the library to latest commit and things are working with no warnings .... thanks
