### ISSUE TITLE
Video preview contained in a navigation controller, is it possible?

### ISSUE THREAD

**Issue by ssaguiar** [yannickl/QRCodeReader.swift#99]
I am using a navigation controller between my views.
The problem is that the video preview of the barcode scanner ocupes all the container.
I am using the scanInModalAction because the scanInPreviewAction doesn't work well.

Is the above possible, or I need to use the cancel button, wHich I disabled?

Thanks for any clue.

**Comment by yannickl** [comment]
I'll close this issue. You should ask this kind of question on stackoverflow.

To quickly answer to you, you can embedded the `QRCodeReader` wherever you want. You can either use the the `QRCodeReaderController` or the `QRCodeReaderView`.
